language: generic
services:
    - docker

before_install:
    - docker build -t bgpark82/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bgpark82/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: ap-northeast-2
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-ap-northeast-2-085853160041"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY